### PR TITLE
DOC: Fix toc in documentation and a typo

### LINKED ISSUE #251: DOC: table of contents is out of sync

### PR DESCRIPTION
**Pull request by avirsaha**
Closes #251

### CODE REVIEW

**Review by neutrinoceros — CHANGES_REQUESTED** [review]
Hi @avirsaha, thanks for your contribution !
Can you please revert the change of style in bullet (`*` -> `-`) ? Other than that, looks good to me !

**Comment by neutrinoceros** [comment]
Also note that I normally generate (and update) this table of contents with a pre-commit hook, it just happens to be commented at the moment, but I think it can be uncommented now (see https://github.com/neutrinoceros/gpgi/blob/main/.pre-commit-config.yaml#L21). If you feel like it, you can also uncomment it here, but it's fine if you don't !
Thanks again !

**Comment by avirsaha** [comment]
Thank you for your review and valuable feedback. I'll make the necessary changes.

**Comment by avirsaha** [comment]
The necessary changes to the TOC style have been made, and I've also uncommented the pre-commit hook you mentioned earlier.

**Comment by neutrinoceros** [comment]
Thank you again !

**Pull request merged**
